/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 5315ef5fc63f285a8d4b01bf7c76e386)
interface __BaseEnv_Env {
	DB: D1Database;
	RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	SEED_ENTROPY: string;
	ENGINE_VERSION: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SEED_ENTROPY" | "ENGINE_VERSION">> {}
}
