/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: ace8f4a3d68b225070cd41dd0cb993c8)
interface __BaseEnv_Env {
	DB: D1Database;
	ANALYTICS: AnalyticsEngineDataset;
	RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
